print(f"*********Welcome To Rock,Paper & Scissors Game*********")
print(f"")
print(f"Winning Rules of Rock,Paper & Scissors game as Follows:")
print(f"Rock vs Paper -> Paper Wins")
print(f"Rock vs Scissors -> Rock Wins")
print(f"Paper vs Scissors -> Scissors Wins")
print(f"")
print(f"*******************************************************")
print(f"")
print(f"*********Round Number1 Starts*********")
print(f"")
print("Enter your Choice")
print("1. Rock")
print("2. Paper")
print("3. Scissors")
a = str(input("User Turn:"))
while(int(a) >= 4):
            a = input("!!!Error! Please enter valid input:")
print(f"User choice is:{a[1]}")
a = str(input("Computer Turn:"))
while(not a.isdigit() or int(a) >= 4):
            a = input("!!!Error! Please enter valid input:")
print(f"Computer choice is:{a[1]}")

